ResumeProj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as home_views
from account import urls as account_urls
from entry import urls as entry_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_views.HomeView.as_view() , name='main_page' ), #Home Page  
    url(r'^account/', include(account_urls)), #All account related urls
    url(r'^about/$', home_views.AboutView.as_view(), name='about'),
    url(r'^contact/$', home_views.ContactView.as_view(), name='contact'),
    url(r'^post/', include(entry_urls) ) ,
]

account/urls.py
from django.conf.urls import url, include
from .views import *
from entry import urls as entry_urls

app_name = "account"

urlpatterns = [
    url(r'^home/$', LoginView.as_view()),
    url(r'^home/(?P<username>\w*)/(?P<page>[0-9]*)$', AccountHomeView.as_view(), name="user"),
    url(r'^login/$', LoginView.as_view(), name = "login"),
    url(r'^logout/$', LogOutView.as_view() ,name='logout'),
    url(r'^register/$', AccountRegisterView.as_view(), name="register"),
    url(r'^search/(?P<username>\w*)/$', SearchAccountView.as_view(),  name = "search"),
    url(r'^settings/$', AccountSettingsView.as_view(), name = "settings"),
    url(r'^settings/change-password/$', ChangePasswordView.as_view(), name = "change_password"),

]

entry/urls.py
from django.conf.urls import url, include
from .views import *

app_name = "entry"

urlpatterns = [
    url(r'^new-post/$', NewEntryView.as_view() , name = 'new_post'),
    url(r'^detail/(?P<pk>[0-9]*)/$', EntryDetailView.as_view(), name='detail' ),
    url(r'^detail/(?P<pk>[0-9]*)/edit/$', EntryEditView.as_view() , name = 'edit'),
    url(r'^detail/(?P<pk>[0-9]*)/delete/$', EntryDeleteView.as_view(), name = 'delete'),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Entry(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.TextField(max_length = 50)
    text = models.TextField(max_length = 300, blank = True, null = True)
    time_created = models.DateTimeField(auto_now_add = True)
    last_updated = models.DateTimeField(auto_now = True)


    def __str__(self):
        return(self.title)

account/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
    
class LoginForm(forms.Form):
 
    username = forms.CharField(max_length = 20)
    password = forms.CharField(widget = forms.PasswordInput)

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget = forms.PasswordInput)
    new_password = forms.CharField(widget = forms.PasswordInput)
    repeat_password = forms.CharField(widget = forms.PasswordInput)

account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, FormView, View, DetailView, ListView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout, mixins
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .forms import *

from .models import *

class AccountHomeView(mixins.LoginRequiredMixin, ListView):
    model = User

    def get_context_data(self,*args, **kwargs):

        page_value = int(self.kwargs['page'])
        next_page = page_value +1
        prev_page = page_value - 1
        request_user = self.request.user
        specified_user = User.objects.get(username = self.kwargs['username'])
        #Returns the only 10 entries per page
        qs = Entry.objects.filter(user=specified_user).order_by('time_created').reverse()[10*page_value-10 : 10*page_value]

        context = {'user': specified_user, 'request_user':request_user, 'entries':qs, 'next_page':next_page , 'prev_page':prev_page}
        return context

    def get_template_names(self):
        if(self.request.user.username == self.kwargs['username']):
            return 'account_home.html'
        else:
            return 'foreign_home.html'


class AccountRegisterView(CreateView):
    form_class = AccountForm
    template_name = 'registration_page.html'
    context_object_name = "form"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(self.request.POST['password'])
        self.object = form.save()

        login( self.request, self.object)

        return HttpResponseRedirect(reverse_lazy( "account:user", kwargs={"username":self.object.username, "page":"1"}))
    
class LoginView(FormView):
    form_class = LoginForm
    template_name = 'login.html'

    def get(self,*args, **kwargs):
        if( self.request.user.is_authenticated() ):
            return HttpResponseRedirect(reverse_lazy('account:user', kwargs={"username":self.request.user.username, "page":"1"}))
        else:
            return render(self.request, self.template_name, {})
    
    
    def post(self, *args, **kwargs):
        filled_form = self.form_class(self.request.POST)

        if(filled_form.is_valid()):
            logged_in_user = authenticate(
                username = filled_form.cleaned_data['username'],
                password = filled_form.cleaned_data['password']
                )
            if(logged_in_user is not None):
                login(self.request, logged_in_user)
                return HttpResponseRedirect(reverse_lazy('account:user', kwargs={"username":self.request.user.username, "page":"1"}))
            else:
                return HttpResponse("Incorrect Username/Password")
            
        else:
            return HttpResponse("Bad form input")

class LogOutView(View):
    
    def get(self, request):
        logout(self.request)
        return HttpResponseRedirect(reverse_lazy('main_page')) 

class SearchAccountView(ListView):
    context_object_name = "search"
    template_name = "search_results.html"

    def post(self, request, *args, **kwargs):
        print('form')

    def get_queryset(self, *args, **kwargs):
        query = self.kwargs['username']
        results = User.objects.filter(username__icontains = self.kwargs['username'])


        return {'query':query , 'results':results}

class AccountSettingsView(mixins.LoginRequiredMixin, TemplateView):    
    template_name = "account_settings.html"

class ChangePasswordView(mixins.LoginRequiredMixin, FormView):
    form_class = ChangePasswordForm
    template_name = 'change_password.html'

    def form_valid(self,form):
        curr_user = self.request.user
        #Checking for correct password
        if not authenticate( username = curr_user, password = form.cleaned_data['old_password']):
            form.add_error(None, ValidationError( ('Incorrect Password'), code='invalid') )
            return super(ChangePasswordView, self).form_invalid(form)

        #Check if new password is identica
        if form.cleaned_data['new_password'] != form.cleaned_data['repeat_password']:
            form.add_error(None, ValidationError( ('Passwords did not match'), code='invalid') )
            return super(ChangePasswordView, self).form_invalid(form)

        curr_user.set_password(form.cleaned_data['new_password'])
        curr_user.save() #Is this needed?

        return HttpResponseRedirect(reverse_lazy('account:user', kwargs={"username":self.request.user.username, "page":"1"}))

account/templates/account_home.html
{% extends 'base.html' %} 

{% block content %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= {% url 'account:user' username=request_user.username page=1 %}> 
          <i class="glyphicon glyphicon-home"></i> Lorem </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href= {% url 'about' %}>About</a>
        </li>
        <li>
          <a href= {% url 'contact' %}>Contact</a>
        </li>

        <li>
          <div class="form-group"> 
          <form action={% url 'account:search' username="" %} name="search_bar">
            <input = "text" name="username" placeholder="Search Profiles..." >

            <button type="submit">Search</button>
          </form>
          </div>
        </li>
       

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list"></span> {{request_user.username}}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-user"></span> Profile</a>
            </li>
            <li>
              <a href={% url 'account:settings' %}>
                <span class="glyphicon glyphicon-cog"></span> Settings</a>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <a href= {% url 'account:logout' %}>
                <span class="glyphicon glyphicon-log-out"></span> Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>

  </div>
</nav>

<div class="container text-center">
  <div class="jumbotron" style="border-style:solid">
    <h1> Latest posts by {{user.username.capitalize}} </h1>
  </div>
  <hr>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10">
      <a href="#" style="color:black">
        <u>Posts</u>
        <i class="glyphicon glyphicon-menu-down"></i>
      </a>
      <hr>
      <!-- Prev/Next Page -->
      <div container>
        {% if prev_page != 0 %}
        <a href= {% url 'account:user' username=user.username page=prev_page %}>
          <i class="glyphicon glyphicon-triangle-left"></i>Prev </a>
        {% endif %}
        <a href= {% url 'account:user' username=user.username page=next_page %}> Next
          <i class="glyphicon glyphicon-triangle-right"></i>
        </a>
      </div>
      <hr>

      <!-- Entries -->

      {% for entry in entries %}
      <h4>
        <!-- <input id="checkBox" type="checkbox" name = {{entry.pk}}> -->
        <a href= {% url 'entry:detail' pk=entry.pk %}>{{entry.title}}</a>
        <a href= {% url 'entry:edit' pk=entry.pk %}>
          <i class="glyphicon glyphicon-pencil"></i>
        </a>
        <a href= {% url 'entry:delete' pk=entry.pk %}>
          <i class="glyphicon glyphicon-trash"></i>
        </a>
      </h4>
      <p>
        Created: {{entry.time_created}}</br>
        Last Updated: {{entry.last_updated}} </br>
      </p>
      <p>{{entry.text}}</p>
      </br>

      <hr> {% endfor %}

    </div>
    <div class="col-lg-2 col-md-2 col-sm-2">
      <ul class="nav navbar-nav" style="background-color:bisque" style="border-style: solid">
        <li>
          <a href= {% url 'entry:new_post' %}>
            <i class="glyphicon glyphicon-plus"></i> New Post </a>
        </li>
        <!-- <li>
          <a href="#">
            <i class="glyphicon glyphicon-pencil"></i> Edit Post </a>
        </li> -->
        <li>
          <a href="#">
            <i class="glyphicon glyphicon-remove"></i> Delete Post </a>
        </li>
      </ul>
    </div>
  </div>

  <!-- Prev/ Next Page -->
  <div container>
    {% if prev_page != 0 %}
    <a href= {% url 'account:user' username=user.username page=prev_page %}>
      <i class="glyphicon glyphicon-triangle-left"></i>Prev </a>
    {% endif %}
    <a href= {% url 'account:user' username=user.username page=next_page %}> Next
      <i class="glyphicon glyphicon-triangle-right"></i>
    </a>
  </div>
  <hr>


</div>

{% endblock %}

account/templates/account_settings.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <a href = {% url 'account:change_password' %}>Change Passwords</a>
</div>
{% endblock %}

account/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Lorem</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <style type = "text/css">
    body {background-color:#d7cec7;}
    hr{border-color:black;}
    a{color:black;}


    {% block style %}
    {% endblock %}

    </style>
    
    <body>

        {% block content %}

        {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

account/templates/change_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>

    </div>

{% endblock %}

account/templates/foreign_home.html
{% extends 'base.html' %} 

{% block content %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= {% url 'account:user' username=request_user.username page=1 %}>
          <i class="glyphicon glyphicon-home"></i> Lorem </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href= {% url 'about' %}>About</a>
        </li>
        <li>
          <a href= {% url 'contact' %}>Contact</a>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list"></span> {{request_user.username}}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-user"></span> Profile</a>
            </li>
            <li>
              <a href={% url 'account:settings' %}>
                <span class="glyphicon glyphicon-cog"></span> Settings</a>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <a href= {% url 'account:logout' %}>
                <span class="glyphicon glyphicon-log-out"></span> Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>

  </div>
</nav>

<div class="container text-center">
  <div class="jumbotron" style="border-style:solid">
    <h1> Latest posts by {{user.username.capitalize}} </h1>
  </div>
  <hr>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10">
      <a href="#" style="color:black">
        <u>Posts</u>
        <i class="glyphicon glyphicon-menu-down"></i>
      </a>
      <hr>
      <!-- Prev/Next Page -->
      <div container>
        {% if prev_page != 0 %}
        <a href= {% url 'account:user' username=user.username page=prev_page %}>
          <i class="glyphicon glyphicon-triangle-left"></i>Prev </a>
        {% endif %}
        <a href= {% url 'account:user' username=user.username page=next_page %}> Next
          <i class="glyphicon glyphicon-triangle-right"></i>
        </a>
      </div>
      <hr>

      <!-- Entries -->

      {% for entry in entries %}
      <h4>
        {{entry.title}}
      </h4>
      <p>
        Created: {{entry.time_created}}</br>
        Last Updated: {{entry.last_updated}} </br>
      </p>
      <p>{{entry.text}}</p>
      </br>

      <hr> {% endfor %}

    </div>
  </div>

  <!-- Prev/ Next Page -->
  <div container>
    {% if prev_page != 0 %}
    <a href= {% url 'account:user' username=user.username page=prev_page %}>
      <i class="glyphicon glyphicon-triangle-left"></i>Prev </a>
    {% endif %}
    <a href= {% url 'account:user' username=user.username page=next_page %}> Next
      <i class="glyphicon glyphicon-triangle-right"></i>
    </a>
  </div>
  <hr>


</div>

{% endblock %}

account/templates/login.html
{% extends 'base.html' %}

{% block content %}
  </br>
    <div class = "container">
        <div class="jumbotron text-center" style="border-style:solid">
            <h1>Login Page</h1>
        </div>
        <hr>

        <div class = "container text-justify">
            <form method = "POST"> {% csrf_token %}
                <label class="text-danger"> {{form.errors}} </label></br>
                <b>Username</b> : <input type="text" name='username'></br></br>
                <b>Password</b> : <input type="password" name='password'></br></br>
            
                <button type = "submit" class="btn btn-default">Login</button>
                <a href = {% url 'main_page' %} class="btn btn-default">Back</a>
            </form>
        </br>
        </div>

    </div>

{% endblock %}

account/templates/registration_page.html
{% extends 'base.html' %}

{% block content %}
  </br>
    <div class = "container">
        <div class="jumbotron text-center" style="border-style:solid">
            <h1>Registration Page</h1>
        </div>
        <hr>

        <div class = "container text-justify">
            <form method = "POST"> {% csrf_token %}
                {{form.as_p}}
                <button type = "submit" class="btn btn-default">Register</button>
                <a href = {% url 'main_page' %} class="btn btn-default">Back</a>

            </form>
        </div>

    </div>
{% endblock %}

account/templates/search_results.html
{% extends 'base.html' %}

{% block content %}
<div class = container>
<h1>Search Results for : "{{search.query}}"</h1>

    <ul>
        {% for result in search.results %}
        <a href = {% url 'account:user' username=result.username page=1 %}>
            <i class="glyphicon glyphicon-eye-open"></i> {{result}}</a> </br>
        {% endfor %}
    </ul>
</div>
{% endblock %}