ResumeProj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as home_views
from account import urls as account_urls
from entry import urls as entry_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_views.HomeView.as_view() , name='main_page' ), #Home Page  
    url(r'^account/', include(account_urls)), #All account related urls
    url(r'^about/$', home_views.AboutView.as_view(), name='about'),
    url(r'^contact/$', home_views.ContactView.as_view(), name='contact'),
    url(r'^post/', include(entry_urls) ) ,
]

account/urls.py
from django.conf.urls import url, include
from .views import *
from entry import urls as entry_urls

app_name = "account"

urlpatterns = [
    url(r'^home/$', LoginView.as_view()),
    url(r'^home/(?P<username>\w*)/(?P<page>[0-9]*)$', AccountHomeView.as_view(), name="user"),
    url(r'^login/$', LoginView.as_view(), name = "login"),
    url(r'^logout/$', LogOutView.as_view() ,name='logout'),
    url(r'^register/$', AccountRegisterView.as_view(), name="register"),
    url(r'^search/(?P<username>\w*)/$', SearchAccountView.as_view(),  name = "search"),
    url(r'^settings/$', AccountSettingsView.as_view(), name = "settings"),
    url(r'^settings/change-password/$', ChangePasswordView.as_view(), name = "change_password"),

]

entry/urls.py
from django.conf.urls import url, include
from .views import *

app_name = "entry"

urlpatterns = [
    url(r'^new-post/$', NewEntryView.as_view() , name = 'new_post'),
    url(r'^detail/(?P<pk>[0-9]*)/$', EntryDetailView.as_view(), name='detail' ),
    url(r'^detail/(?P<pk>[0-9]*)/edit/$', EntryEditView.as_view() , name = 'edit'),
    url(r'^detail/(?P<pk>[0-9]*)/delete/$', EntryDeleteView.as_view(), name = 'delete'),
]

ResumeProj/views.py
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


class HomeView(TemplateView):
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        if(self.request.user.is_authenticated()):
            return HttpResponseRedirect(reverse_lazy('account:user', kwargs={"username":self.request.user.username, 'page':'1'}))
        else:
            return super(HomeView, self).get(request, *args, **kwargs)

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

ResumeProj/templates/about.html
{% extends 'base.html' %}

{% block content %}
<body>
  <!-- Biography/About -->
  </br>
  <div class="container" style="background-color:ghostwhite">
    </br>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="container-fluid">
          <h1 class="page-header">
            Jack Chen
          </h1>
          <img src="https://i.imgur.com/XIGuHEN.png" class="img-rounded" alt="THATS ME!" width="200" height="236"> 
        </div>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-9">
        <div class="container-fluid text-justify">
          <p>
            This is a website created by Computer Science student Jack Chen of Hunter College (Nov.26). The backend of the site is powered by the Django framework
            and the design of the pages were made using Twitter's Bootstrap API.
          </p>
          <hr>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio natus, totam ad cumque libero sint obcaecati, impedit, nemo
            minima incidunt quae quas nesciunt porro itaque velit necessitatibus facere. Quas, ut. Lorem ipsum, dolor sit
            amet consectetur adipisicing elit. Nobis, dolores nam nesciunt, officiis voluptas sint, optio beatae sapiente
            quidem hic voluptates tenetur omnis ab quod dolorem voluptate? Quae, dolor architecto. Lorem ipsum dolor sit,
            amet consectetur adipisicing elit. Aperiam quasi aliquam officia obcaecati et voluptate quae ipsa? Accusantium
            sapiente, iusto quibusdam eos, suscipit enim temporibus exercitationem fuga dicta vero nesciunt!
          </p>
        </div>

      </div>
    </div>
    </br>
    <a href= {% url 'main_page' %} class="btn btn-default">Back</a>
    </br>
    </br>
  </div>

 {% endblock %}

ResumeProj/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Lorem</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <style type = "text/css">
    body {background-color:#d7cec7;}
    hr{border-color:black;}
    a{color:black;}

    {% block style %}
    {% endblock %}

    </style>
    
    <body>

        {% block content %}

        {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

ResumeProj/templates/contact.html
{% extends 'base.html' %} {% block content %}

</br>
<div class="container" style="background-color:ghostwhite">
  <h1>
    <u>Contacts</u>
  </h1>
  <p>
    <strong>Name: </strong> Jack Chen </br>
    <strong>Email: </strong> Chen.Jack.cs.@gmail.com </br>
    <strong>Phone Number: </strong> 917-776-8090 </br>
    <strong>Past Projects: </strong> Github.com/Chen-Jack </br>
    <strong>LinkedIn: </strong> https://www.linkedin.com/in/jack-chen-07019191/
  </p>

  <a href= {% url 'main_page' %} class="btn btn-default">Back</a>
  </br>
  </br>
</div>

{% endblock %}

ResumeProj/templates/home.html
{% extends 'base.html' %}

{% block style %}
  .jumbotron{
    margin-top: 20px;
    border-style: solid;
    border-color: black;
    background-image: url('http://i.imgur.com/5ahTckK.jpg?1');
    background-size: cover;
    color: beige;
  }

{% endblock %}



{% block content %}
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"> Lorem </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href= {% url 'about' %}>About
            </a>
          </li>
          <li>
            <a href= {% url 'contact' %}>Contact</a>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href= {% url 'account:register' %}>
              <span class="glyphicon glyphicon-user"></span> Sign Up</a>
          </li>
          <li>
            <a href= {% url 'account:login' %}>
              <span class="glyphicon glyphicon-log-in"></span> Login</a>
          </li>
        </ul>
      </div>


    </div>

  </nav>
  <div class="container-fluid">
    <div class="jumbotron text-center">
      <h1>Lorem, ipsum dolor.</h1>
      <p> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae, quo?</p>

      <a href= {% url 'about' %} class="btn btn-default">Read More</a>
    </div>
    <hr>

    <div class="text-center">
      <a href= {% url 'account:register' %} class="btn btn-default">
        <span class="glyphicon glyphicon-user"></span> Sign Up </a>
      </br>
      </br>
      <a href= {% url 'account:login' %} class="btn btn-default">
        <span class="glyphicon glyphicon-log-in"></span> Log In </a>
    </div>
  </div>

{% endblock %}

ResumeProj/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Register</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <style type = "text/css">
    body {background-color: #96777d;}

    </style>

</head>

  <body>
    <div class = "container">
        <h1>Login Page</h1>
        <hr>

        <div class = "container text-justify">
            <form method = "POST"> {% csrf_token %}
                <label class="text-danger"> {{form.errors}} </label></br>
                <b>Username</b> : <input type="text" name='username'></br></br>
                <b>Password</b> : <input type="password" name='password'></br></br>
            
                <button type = "submit">Login</button>
            </form>
        </br>
            <a href = 'http://127.0.0.1:8000/' class="btn btn-default">Back</a>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

ResumeProj/templates/registration_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Register</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <style type = "text/css">
    body {background-color: #96777d;}

    </style>

</head>

  <body>
    <div class = "container">
        <div class="container panel">
            <h1>Registration Page</h1>
        </div>
        <hr>

        <div class = "container text-justify">
            <form method = "POST"> {% csrf_token %}
                {{form.as_p}}
                <button type = "submit" class="btn btn-default">Register</button></br></br>
            </form>

            <a href = 'http://127.0.0.1:8000/' class="btn btn-default">Back</a>
        </div>


    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>